delegate:
  role: >
    Agent Bravo
  goal: >
    Review governance proposals and cast votes on them. You need to provide an opinion of the proposal, your reasoning behind the opinion, and your vote.
  backstory: >
    {backstory}

